"""
Ren'Py hooks generator.
Produces the hooks.rpy file that injects dictionary-based translations at runtime.
"""

import os


HOOKS_TEMPLATE = '''# =============================================================================
# DeepRenPyTrans — Runtime Translation Hooks
# Generated by DeepRenPyTrans (https://github.com/Danko-Novak/DeepRenPyTrans)
# Place this file in: game/tl/{lang_dir}/hooks.rpy
# =============================================================================

init -1 python:
    import json
    import os

    # Auto-set language on first run
    if getattr(persistent, "deeprenpytrans_lang_set", None) is None:
        _preferences.language = "{lang_dir}"
        persistent.deeprenpytrans_lang_set = True

    # Hotkey '{hotkey}' to toggle translation on/off
    def _deeprenpytrans_toggle():
        lang = None if _preferences.language == "{lang_dir}" else "{lang_dir}"
        renpy.run(Language(lang))

    config.underlay.append(
        renpy.Keymap({keymap_args})
    )

    class _DeepTranslator(object):
        """Dictionary-based runtime text translator."""

        def __init__(self):
            self.translations = {{}}
            self._load()

        def _load(self):
            try:
                with renpy.file("tl/{lang_dir}/dictionary.json") as f:
                    content = f.read()
                    if isinstance(content, bytes):
                        content = content.decode("utf-8")
                    self.translations = json.loads(content)
            except Exception:
                pass

        def translate(self, text):
            if not isinstance(text, str) or not text:
                return text
            return self.translations.get(text, text)

    if "_deep_trans" not in globals():
        _deep_trans = _DeepTranslator()

    def _deeprenpytrans_filter(text):
        if _preferences.language == "{lang_dir}":
            return _deep_trans.translate(text)
        return text

    config.say_menu_text_filter = _deeprenpytrans_filter
    config.replace_text = _deeprenpytrans_filter


# --- PHASE 2: Logging + Font Overrides (higher init priority) ---
init 5 python:
    import os
    import codecs

    # Logger for strings not found in dictionary
    _untranslated_log_path = None
    if getattr(config, "basedir", None):
        _untranslated_log_path = os.path.join(config.basedir, "game", "untranslated.log")
    _logged_untranslated = set()

    def _log_untranslated(text):
        if not _untranslated_log_path:
            return
        if not text or not isinstance(text, str):
            return
        if text in _logged_untranslated:
            return
        clean = text.strip()
        if len(clean) < 2 and clean not in ["?", "!", "."]:
            return
        _logged_untranslated.add(text)
        try:
            with codecs.open(_untranslated_log_path, "a", "utf-8") as f:
                f.write(text + "\\n")
        except Exception:
            pass

    def _deeprenpytrans_safe_filter(text):
        if _preferences.language != "{lang_dir}":
            return text
        translated = _deep_trans.translate(text)
        if text and isinstance(text, str) and text not in _deep_trans.translations:
            _log_untranslated(text)
        return translated

    # Override with logging-enabled filter
    config.say_menu_text_filter = _deeprenpytrans_safe_filter
    config.replace_text = _deeprenpytrans_safe_filter

    # Font overrides for target language
    if _preferences.language == "{lang_dir}":
        _font_to_use = "{default_font}"
        if renpy.exists(_font_to_use):
            gui.text_font = _font_to_use
            gui.name_text_font = _font_to_use
            gui.interface_text_font = _font_to_use
            gui.button_text_font = _font_to_use
            gui.choice_button_text_font = _font_to_use
            style.default.font = _font_to_use
{font_replacements}
'''


def generate_hooks(
    output_dir: str,
    lang_dir: str = "russian",
    hotkey: str = "ctrl_alt_t",
    default_font: str = "DejaVuSans.ttf",
    font_replacements: dict = None,
    verbose: bool = False,
) -> str:
    """
    Generate a hooks.rpy file for runtime translation injection.

    Args:
        output_dir: Directory to write hooks.rpy (usually game/tl/<lang>/).
        lang_dir: Translation directory name (e.g., "russian", "spanish").
        hotkey: Key to toggle translation.
        default_font: Default fallback font.
        font_replacements: Dict mapping original fonts to replacement fonts.
        verbose: Print progress.

    Returns:
        Path to the generated hooks.rpy file.
    """
    # Build font replacement lines
    font_lines = ""
    if font_replacements:
        for original, replacement in font_replacements.items():
            font_lines += f'        if renpy.exists("{replacement}"):\n'
            font_lines += f'            config.font_replacement_map["{original}"] = ("{replacement}", False, False)\n'

    if len(hotkey) == 1:
        keymap_args = f"{hotkey}=_deeprenpytrans_toggle, {hotkey.upper()}=_deeprenpytrans_toggle"
    else:
        keymap_args = f"{hotkey}=_deeprenpytrans_toggle"

    content = HOOKS_TEMPLATE.format(
        lang_dir=lang_dir,
        hotkey=hotkey,
        keymap_args=keymap_args,
        default_font=default_font,
        font_replacements=font_lines,
    )

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "hooks.rpy")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    if verbose:
        print(f"✅ Generated {output_path}")

    return output_path
